language: node_js
matrix:
    include:
        - os: linux
          dist: xenial
        - os: osx
        - os: windows
node_js:
    - 'lts/*'
branches:
    only:
        - master
install:
    - npm install -g
script:
    - create-apex-js-app testApp -s -p && cd testApp
