language: node_js
dist: xenial
node_js:
    - 'lts/*'
branches:
    only:
        - master
        - /^greenkeeper/.*$/
install:
    - npm install -g
script:
    - create-apex-js-app testApp -s && cd testApp && npm run build
