language: node_js
os:
  - linux
  dist: xenial
  - osx
  - windows
node_js:
    - 'lts/*'
branches:
    only:
        - master
install:
    - npm install -g
script:
    - create-apex-js-app testApp -s -p && cd testApp
